#ifndef NATIVE_WUCLASSESH
#define NATIVE_WUCLASSESH

#include <wkpf_wuclasses.h>

#define ENABLE_WUCLASS_GENERIC
#define ENABLE_WUCLASS_THRESHOLD
#define ENABLE_WUCLASS_NUMERIC_CONTROLLER
#define ENABLE_WUCLASS_LIGHT
#define ENABLE_WUCLASS_LIGHT_SENSOR

uint8_t native_wuclasses_init();

#endif // NATIVE_WUCLASSESH