import java.io.*;
import nanovm.avr.*;
import nanovm.wkpf.*;
import nanovm.lang.Math;

public class {{ applicationName }} {

    // =========== Begin: Generated by the translator from application WuML
    /* Component instance IDs to indexes:
    {% for instance in wuObjectList %}
    {{ instance.instanceId }} => {{ instance.instanceIndex }}
    {% endfor %}
    */

    //link table
    // fromInstanceIndex(2 bytes), fromPropertyId(1 byte), toInstanceIndex(2 bytes), toPropertyId(1 byte), toWuClassId(2 bytes)
    //eg. (byte)0,(byte)0, (byte)0, (byte)2,(byte)0, (byte)1, (byte)1,(byte)0
    private final static byte[] linkDefinitions = {
        // Note: Component instance id and wuclass id are little endian
        // Note: using WKPF constants now, but this should be generated as literal bytes by the WuML->Java compiler.
        // Connect input controller to threshold
        {% for link in wuLinks %}
        {{ link.toJava() }}{{ ',' if not loop.last else '' }}
        {% endfor %}
    };

    private final static byte[] componentInstanceToWuObjectAddrMap = {
        {% for object in wuObjectList %}
        {{ object.toJava() }}{{ ',' if not loop.last else '' }}
        {% endfor %}
    };
    // =========== End: Generated by the translator from application WuML

    public static void main (String[] args) {
        System.out.println("{{ applicationName }}");
        WKPF.loadComponentToWuObjectAddrMap(componentInstanceToWuObjectAddrMap);
        WKPF.loadLinkDefinitions(linkDefinitions);
        initialiseLocalWuObjects();

        while(true){
            VirtualWuObject wuclass = WKPF.select();
            if (wuclass != null) {
                wuclass.update();
            }
        }
    }

    private static void initialiseLocalWuObjects() {
        {% for object in wuObjectList %}
        {% if object.wuClass.isSoft() %}

        {% if object.wuClass.isVirtual() %}
        WKPF.registerWuClass(WKPF.{{ object.wuClass.wuClassDef.getJavaConstName() }}, {{ object.wuClass.wuClassDef.getJavaGenClassName() }}.properties);
        {% endif %}

        if (WKPF.isLocalComponent((short){{ object.instanceIndex }})) {
            {% if object.wuClass.isVirtual() %}
            VirtualWuObject wuclassInstance{{ object.wuClass.wuClassDef.getWuClassName() }} = new {{ object.wuClass.wuClassDef.getJavaGenClassName() }}();
            WKPF.createWuObject((short)WKPF.{{ object.wuClass.wuClassDef.getJavaConstName() }}, WKPF.getPortNumberForComponent((short){{ object.instanceIndex }}), wuclassInstance{{ object.wuClass.wuClassDef.getWuClassName() }});
            {% else %}
            WKPF.createWuObject((short)WKPF.{{ object.wuClass.wuClassDef.getJavaConstName() }}, WKPF.getPortNumberForComponent((short){{ object.instanceIndex }}), null);
            {% endif %}

            {% for property in object.wuClass.wuClassDef.properties.values() %}
            {% if property.default_value != '' %}
            {% if property.datatype == 'boolean' %}
            WKPF.setPropertyBoolean((short){{ object.instanceIndex }}, WKPF.{{ property.getJavaConstName() }}, {{ str(property.default_value).lower() }});
            {% elif property.datatype == 'int' %}
            WKPF.setPropertyShort((short){{ object.instanceIndex }}, WKPF.{{ property.getJavaConstName() }}, (short){{ property.default_value }});
            {% elif property.datatype == 'short' %}
            WKPF.setPropertyShort((short){{ object.instanceIndex }}, WKPF.{{ property.getJavaConstName() }}, (short){{ property.default_value }});
            {% elif property.datatype == 'refresh_rate' %}
            WKPF.setPropertyRefreshRate((short){{ object.instanceIndex }}, WKPF.{{ property.getJavaConstName() }}, (short){{ str(property.default_value) }});
            {% else %}
            WKPF.setPropertyShort((short){{ object.instanceIndex }}, WKPF.{{ property.getJavaConstName() }}, (short){{ property.default_value }});
            {% endif %}

            {% endif %}
            {% endfor %}
        }
        {% endif %}
        {% endfor %}
    }
}
